services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meal_prep
    volumes:
      - meal_prep_mysql:/var/lib/mysql

volumes:
  meal_prep_mysql:
